== Research Computing

This resource contains teaching materials for an overview course in 
*research computing*.

=== Audience

The target audience is primarily college students, particularly graduate 
students, who conduct academic or scientific research. The information will 
also be useful for working professionals.

=== Course Goals

The main goal of this course is to help students improve their technical 
readiness for engaging in the increasingly data-centric work that they face 
in their degree programs, in their related research, and in their future 
professional and research practice. Students will become acquainted with 
key concepts in research computing and data management, including overviews 
of systems analysis techniques, data security and integrity, and database 
tools, among others.

=== Learning Objectives

At the end of this course students should be able to:

* Analyze requirements for management of data in different situations and projects.
* Choose appropriate technical tools and techniques to support that data management.
* Identify hazards and pitfalls in data-related projects.
* Identify factors that affect performance in the collection and preparation of data for analysis.
* Describe the core technologies most frequently employed in large-scale research data management.

=== File Contents

The files hosted in the repository consist of the presentation slides in 
Markdown format as well as transcripts to go with those slides. The transcripts 
are posted as wiki pages in ASCIIDoc format and are also offered as PDF and Epub 
eBooks.

=== The Research Computing Team

Thanks to the following people who have contributed to this resource (in
no particular order):

_Brian High, Jim Hogan, John Yocum, Elliot Norwood, and Lianne Sheppard_

=== Copyright, License and Disclaimer

Copyright © The https://github.com/brianhigh/research-computing[Research Computing
Team]. This information is provided for educational purposes
only. See
https://github.com/brianhigh/research-computing/blob/master/LICENSE[LICENSE]
for more information.
https://creativecommons.org/licenses/by/4.0/[Creative Commons
Attribution 4.0 International Public License].
